# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
from snakemake.utils import min_version

min_version("6.5")


report: "report/workflow.rst"


rule all:
    input:
        expand(
            "results/individual_calls/{joint_calling_group}.vcf.gz",
            joint_calling_group=joint_calling_group_lists.index,
        ),


include: "rules/common.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/qc.smk"
